name: Implementación automatizada

on:
  pull_request:
    types:
      - closed
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    if: (github.event_name == 'pull_request' && github.event.pull_request.merged == true) || github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.16.0'

      - name: Instalar dependencias
        run: npm install --force

      - name: Subir archivos al servidor (directorio temporal)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "/opt/license/license-manager/"
          debug: true

      - name: Mover archivos y establecer permisos en el VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            npm run build
            pm2 delete 0
            pm2 start npm --name license
